<a href="https://colab.research.google.com/github/Mariyathk/Learn.PY-01/blob/main/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [10]:
import numpy as np
b = np.array(["blue","blue","red","blue"])
b_bool = b == "red"
b_bool

array([False, False,  True, False])

In [12]:
import numpy as np

b = np.array(["blue", "blue", "red", "blue"])
b_bool_1 = []

for x in b:
    if 'red' in x:
        b_bool_1.append(True)
        continue
    b_bool_1.append(False)

b_bool = np.array(b_bool_1)
print(b_bool)

[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [13]:
import numpy as np
arr_1 = np.arange(0,6)
arr_2 = np.arange(6,11)
np.append(arr_1,arr_2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [14]:
import numpy as np
arr_1 = np.arange(0,8).reshape(2,4)
arr_2 = np.arange(8,16).reshape(2,4)
ar1 = np.append(arr_1,arr_2,axis = 0)
ar2 = np.append(arr_1,arr_2,axis = 1)
print(ar1)
print(ar2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]


In [15]:
import numpy as np

arr1 = np.array([x for x in range(0, 8)]).reshape(2, 4)
arr2 = np.array([x for x in range(8, 16)]).reshape(2, 4)

con = np.concatenate((arr1, arr2), axis=0)
con1 = np.concatenate((arr1, arr2), axis=1)
print('axis - 0:\n', con)
print('axis - 1 :\n', con1)

axis - 0:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
axis - 1 :
 [[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
