<a href="https://colab.research.google.com/github/Mariyathk/Learn.PY-01/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [10]:
import numpy as np
n1 = np.array([[2,4,6],[7,2,9],[6,9,0]])
n2 = np.array([[1,2,3],[2,1,4],[6,4,7]])

print(n1)
print(n2)

n3 = n1.dot(n2)
print(n3)

n4 = np.transpose(n3)
print(n4)

[[2 4 6]
 [7 2 9]
 [6 9 0]]
[[1 2 3]
 [2 1 4]
 [6 4 7]]
[[46 32 64]
 [65 52 92]
 [24 21 54]]
[[46 65 24]
 [32 52 21]
 [64 92 54]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [16]:
import numpy
M_1 = numpy.array([[55,25,15],[30,44,2],[11,45,77]])
print(M_1)

M_2 = numpy.linalg.det(M_1)
print(M_2)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180.0000000001
