<a href="https://colab.research.google.com/github/Mariyathk/Learn.PY-01/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [11]:
import numpy as np
x = np.arange(0,16).reshape(4,4)
print(x)

#split it equally along horizontal
x_a = np.vsplit(x,2)
print(x_a)

#split it as 4 parts vertically
x_b = np.hsplit(x,4)
print(x_b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [21]:
import numpy as np
num = np.random.rand(3,3)
print(num)


# Find the ceil of the matrix
num_a = np.ceil(num)
print(num_a)


# Find the floor of the matrix
num_b = np.floor(num)
print(num_b)

[[0.15038058 0.54066531 0.31081481]
 [0.23799361 0.98625456 0.20355489]
 [0.90609037 0.56091401 0.48468286]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [36]:
import numpy as np
rd = np.empty([1,4],dtype=int)
print('Matrix:\n ', rd)
print(rd.shape)
print(rd.dtype)


rd_a = np.squeeze(rd)
print(rd_a)
print(rd_a.shape)

rd_b = np.expand_dims(rd, axis=1)
print(rd_b)
print(rd_b.shape)


Matrix:
  [[1 1 1 0]]
(1, 4)
int64
[1 1 1 0]
(4,)
[[[1 1 1 0]]]
(1, 1, 4)
