<a href="https://colab.research.google.com/github/Mariyathk/Learn.PY-01/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [2]:
import numpy as np
a = np.array([[3,"fun",6],[9,1,4],[4,6,8]])
print(a)

[['3' 'fun' '6']
 ['9' '1' '4']
 ['4' '6' '8']]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [10]:
import numpy as np
mt = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[8,6,9,0]])
print(mt)

#Reshaping 4X4 array into 2X8 array vertically
mt_1 = mt.reshape(8,2)
print("Reshaped array, a: \n ",mt_1)


#Reshaping 4X4 array into 4X4 array horizontally
mt_2 = mt.reshape(2,8)
print("Reshape array, b : \n",mt_2)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [8 6 9 0]]
Reshaped array, a: 
  [[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 8]
 [7 6]
 [8 6]
 [9 0]]
Reshape array, b : 
 [[1 2 3 4 5 6 7 8]
 [9 8 7 6 8 6 9 0]]
